name: Update snake commit graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # This runs once every hour

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: generate snake
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake-catppuccin-mocha.svg?color_snake=#f5c2e7&color_dots=#312c42,#62537f,#8570a6,#a88bcf,#cba6f7
            snake-github-light.svg?palette=github-light

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update snake commit graph" || exit 0
          git push origin main
